#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["mlx-audio", "parakeet-mlx==0.5.2", "huggingface_hub[hf_xet]", "supertonic==1.3.1", "soundfile", "sounddevice", "webrtcvad-wheels", "numpy", "psutil", "misaki[en]"]
# ///
import argparse, json, os, re, subprocess, tempfile, time
from pathlib import Path

from local_audio import load_stt, load_tts, synthesize
from voice_agent import Microphone, play_audio, transcribe_pcm
import voice_tool_agent as base

ROOT = Path(__file__).resolve().parent.parent
SKILL_NAME = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
REPOSITORY = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")
ANSI = re.compile(r"\x1b\[[0-9;]*m")

SKILL_TOOLS = [
    {"type":"function","function":{"name":"list_installed_skills","description":"List skills currently available to this voice agent and Codex.","parameters":{"type":"object","properties":{},"required":[]}}},
    {"type":"function","function":{"name":"search_skill_catalog","description":"Search the live skills.sh catalog for installable skills. Use before proposing an unknown skill.","parameters":{"type":"object","properties":{"query":{"type":"string","description":"What capability to find"}},"required":["query"]}}},
    {"type":"function","function":{"name":"read_installed_skill","description":"Read an installed skill's instructions so they can be followed immediately in this conversation.","parameters":{"type":"object","properties":{"name":{"type":"string","description":"Exact or spoken installed skill name"}},"required":["name"]}}},
    {"type":"function","function":{"name":"display_and_save_text","description":"Display generated text or ASCII art in the terminal and save the exact same content as a text file in the Demo 13 output folder.","parameters":{"type":"object","properties":{"filename":{"type":"string","description":"Simple .txt filename"},"content":{"type":"string","description":"Complete text to display and save"}},"required":["filename","content"]}}},
    {"type":"function","function":{"name":"generate_aski_art","description":"Compatibility tool for ASKI/ASCII-art skills. Display completed ASCII art in the terminal and save it as a text file.","parameters":{"type":"object","properties":{"filename":{"type":"string","description":"Simple .txt filename"},"content":{"type":"string","description":"Complete ASCII art generated by the model"}},"required":["filename","content"]}}},
    {"type":"function","function":{"name":"install_skill","description":"Immediately install an exact skills.sh skill after the user explicitly asks to install it.","parameters":{"type":"object","properties":{"repository":{"type":"string","description":"Exact GitHub owner/repository"},"skill":{"type":"string","description":"Exact skill slug"}},"required":["repository","skill"]}}},
    {"type":"function","function":{"name":"create_skill","description":"Immediately create a new Codex skill after the user explicitly asks to create it.","parameters":{"type":"object","properties":{"name":{"type":"string","description":"Lowercase hyphenated skill name"},"description":{"type":"string","description":"When and why the skill should be used"},"instructions":{"type":"string","description":"Complete reusable imperative Markdown procedure, not example output; only reference tools available in this session"}},"required":["name","description","instructions"]}}},
]
TOOLS = base.TOOLS + SKILL_TOOLS

def skill_roots():
    custom = os.getenv("DEMO13_SKILLS_DIR")
    roots = [Path(custom).expanduser()] if custom else [Path.home()/".codex/skills", Path.home()/".codex/skills/.system", Path.home()/".agents/skills"]
    roots.append(ROOT/"skills")
    return roots

def skill_path(name):
    if not SKILL_NAME.fullmatch(name): raise ValueError("Skill name must be lowercase and hyphenated")
    for root in skill_roots():
        candidate = root/name/"SKILL.md"
        if candidate.is_file(): return candidate
    return None

def normalized_name(name):
    return re.sub(r"[^a-z0-9]", "", name.casefold())

def frontmatter_value(text):
    return json.dumps(" ".join(text.strip().split()), ensure_ascii=False)

def list_installed_skills():
    found = {}
    for root in skill_roots():
        if not root.exists(): continue
        for file in root.glob("*/SKILL.md"):
            name = file.parent.name
            if name not in found:
                content = file.read_text(errors="replace")[:2500]
                match = re.search(r"(?m)^description:\s*(.+)$", content)
                description = match.group(1).strip().strip('"') if match else ""
                found[name] = {"name":name, "description":description, "path":str(file)}
    return {"count":len(found), "skills":sorted(found.values(), key=lambda item:item["name"])}

def run_catalog(arguments, timeout=30):
    environment = os.environ.copy()
    environment.update({"DISABLE_TELEMETRY":"1", "CI":"1", "NO_COLOR":"1"})
    completed = subprocess.run(arguments, cwd=ROOT, env=environment, text=True,
                               stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=timeout)
    output = ANSI.sub("", completed.stdout)
    if completed.returncode: raise RuntimeError(output.strip()[-1000:] or "skills command failed")
    return output

def search_skill_catalog(query):
    query = " ".join(query.split())
    if not query or len(query) > 100 or query.startswith("-"): raise ValueError("Use a short capability query")
    output = run_catalog(["npx", "skills", "find", query])
    results = []
    terms = {term for term in re.findall(r"[a-z0-9]+", query.casefold()) if len(term) > 2}
    pattern = re.compile(r"^([\w.-]+/[\w.-]+)@([\w.-]+)\s+(.+ installs)$")
    for line in output.splitlines():
        match = pattern.match(line.strip())
        if match:
            repository, skill, popularity = match.groups()
            results.append({"repository":repository, "skill":skill, "popularity":popularity,
                            "url":f"https://skills.sh/{repository}/{skill}",
                            "installed":SKILL_NAME.fullmatch(skill) is not None and skill_path(skill) is not None})
    results.sort(key=lambda item: sum(term in f'{item["repository"]} {item["skill"]}'.casefold() for term in terms), reverse=True)
    return {"query":query, "results":results[:5], "source":"skills.sh"}

def read_installed_skill(name):
    path = skill_path(name) if SKILL_NAME.fullmatch(name) else None
    if not path:
        spoken = normalized_name(name)
        matches = []
        for item in list_installed_skills()["skills"]:
            candidate = normalized_name(item["name"])
            if spoken and (spoken in candidate or candidate in spoken): matches.append(item)
        if len(matches) == 1: path = Path(matches[0]["path"]); name = matches[0]["name"]
    if not path: raise ValueError(f"Skill '{name}' is not installed")
    content = path.read_text(errors="replace")
    if len(content) > 12000: content = content[:12000] + "\n[truncated]"
    return {"name":name, "path":str(path), "instructions":content}

def install_skill(repository, skill):
    repository = repository.removeprefix("https://github.com/").removesuffix(".git").strip("/")
    if not REPOSITORY.fullmatch(repository): raise ValueError("Repository must be an exact GitHub owner/repository")
    if not SKILL_NAME.fullmatch(skill): raise ValueError("Skill must be an exact lowercase slug")
    return install_pending({"kind":"install", "repository":repository, "skill":skill})

def build_skill_markdown(name, description, instructions):
    instructions = instructions.strip()
    if not instructions: raise ValueError("Skill instructions cannot be empty")
    lines = instructions.splitlines()
    if lines and lines[0].startswith("# "):
        lines = lines[1:]
        while lines and not lines[0].strip(): lines.pop(0)
        instructions = "\n".join(lines)
    return (f"---\nname: {name}\ndescription: {frontmatter_value(description)}\n---\n\n"
            f"# {name.replace('-', ' ').title()}\n\n{instructions}\n")

def create_skill(name, description, instructions):
    if not SKILL_NAME.fullmatch(name): raise ValueError("Name must use lowercase letters, digits, and hyphens")
    if skill_path(name): raise ValueError(f"Skill '{name}' already exists; this demo never overwrites skills")
    markdown = build_skill_markdown(name, description, instructions)
    if len(markdown) > 20000: raise ValueError("Skill draft is too long")
    target = skill_roots()[0]/name/"SKILL.md"
    print(base.paint("\n  new skill ───────────────────────────────────────", "36"))
    print(markdown.rstrip())
    print(base.paint("  ─────────────────────────────────────────────────", "36"), flush=True)
    return create_pending({"kind":"create", "name":name, "target":str(target), "markdown":markdown})

def display_and_save_text(filename, content):
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,80}\.txt", filename):
        raise ValueError("Filename must be a simple .txt name without directories")
    if not content.strip(): raise ValueError("Content cannot be empty")
    if len(content) > 30000: raise ValueError("Content is too long")
    output_root = Path(os.getenv("DEMO13_OUTPUT_DIR", ROOT/"outputs/demo-13")).expanduser().resolve()
    output_root.mkdir(parents=True, exist_ok=True)
    target = output_root/filename
    target.write_text(content)
    print(base.paint("\n  artifact   ──────────────────────────────────────", "36"))
    print(content.rstrip())
    print(base.paint("  ─────────────────────────────────────────────────", "36"), flush=True)
    return {"status":"displayed_and_saved", "path":str(target), "characters":len(content)}

def install_pending(action):
    repository, skill = action["repository"], action["skill"]
    print(base.paint(f"  installing https://github.com/{repository} ({skill})", "35"), flush=True)
    output = run_catalog(["npx", "skills", "add", f"https://github.com/{repository}",
                          "--skill", skill, "--global", "--agent", "codex", "--yes", "--copy", "--json"], 120)
    installed = skill_path(skill)
    if not installed: raise RuntimeError("Installer finished but the skill was not found on disk")
    return {"status":"installed", "skill":skill, "repository":repository, "path":str(installed),
            "installer_output":output[-1200:]}

def create_pending(action):
    target = Path(action["target"])
    root = skill_roots()[0].resolve()
    if root not in target.resolve().parents: raise ValueError("Refusing to write outside the configured skills directory")
    if target.exists(): raise FileExistsError("Skill appeared after drafting; refusing to overwrite it")
    target.parent.mkdir(parents=True, exist_ok=False)
    target.write_text(action["markdown"])
    return {"status":"created", "skill":action["name"], "path":str(target)}

SKILL_FUNCTIONS = {
    "list_installed_skills":lambda: list_installed_skills(),
    "search_skill_catalog":search_skill_catalog,
    "read_installed_skill":read_installed_skill,
    "display_and_save_text":display_and_save_text,
    "generate_aski_art":display_and_save_text,
}

def stream_turn(messages):
    body = {"model":base.MODEL,"messages":messages,"tools":TOOLS,"stream":True,"think":False,
            "keep_alive":"10m","options":{"temperature":0.15,"num_predict":220}}
    request = base.urllib.request.Request(base.OLLAMA + "/api/chat", data=json.dumps(body).encode(), headers={"Content-Type":"application/json"})
    content, calls, began = [], [], False
    with base.urllib.request.urlopen(request, timeout=180) as response:
        for line in response:
            event = json.loads(line); message = event.get("message", {})
            token = message.get("content", "")
            if token:
                if not began: print(base.paint("  response   ", "32"), end="", flush=True); began = True
                print(token, end="", flush=True); content.append(token)
            calls.extend(message.get("tool_calls") or [])
    if began: print(flush=True)
    return "".join(content).strip(), calls

def expected_skill_tool(text):
    lowered = text.casefold()
    words = set(re.findall(r"[a-zåäö0-9-]+", lowered))
    mentions_skill = bool(words & {"skill", "skills", "skillen", "färdighet", "färdigheten", "färdigheter"})
    if not mentions_skill: return None
    if words & {"sök", "hitta", "search", "find"}: return "search_skill_catalog"
    if words & {"installerade", "installed", "lista", "list", "vilka", "which"}: return "list_installed_skills"
    uses_existing = bool(words & {"använd", "använda", "use", "using", "run", "kör"}) or bool(
        re.search(r"\b(med|with|using)\s+(den\s+|the\s+)?(skillen|skill|färdigheten)\b", lowered)
    )
    if uses_existing: return "read_installed_skill"
    wants_create = bool(words & {"skapa", "create", "make", "bygg", "build"})
    if wants_create: return "create_skill"
    if words & {"installera", "install"}: return "install_skill"
    return None

def run_skill_agent(text, history, skill_prompt):
    started = time.perf_counter()
    expected, corrected = expected_skill_tool(text), False
    skill_loaded, execution_corrected = False, False
    messages = [{"role":"system","content":skill_prompt}] + history + [{"role":"user","content":text}]
    for step in range(1, 7):
        print(base.paint(f"  thinking   model step {step}...", "33"), flush=True)
        content, calls = stream_turn(messages)
        if not calls:
            if expected and not corrected:
                print(base.paint(f"  guardrail  explicit request requires {expected}; retrying", "31"), flush=True)
                messages.append({"role":"assistant","content":content})
                messages.append({"role":"system","content":f"You have access to this capability. You must call {expected} now. Do not refuse, narrate, or ask for confirmation."})
                corrected = True
                continue
            refusal = any(phrase in content.casefold() for phrase in ("kan inte", "inte tillgång", "behöver hjälp", "aktivera", "cannot", "don't have access"))
            if skill_loaded and refusal and not execution_corrected:
                print(base.paint("  guardrail  loaded skill must be executed; retrying", "31"), flush=True)
                messages.append({"role":"assistant","content":content})
                messages.append({"role":"system","content":"The skill is already active. Execute its requested outcome now with an available tool. For ASCII art, generate the content yourself and call generate_aski_art or display_and_save_text. Never ask for activation or confirmation."})
                execution_corrected = True
                continue
            print(base.paint(f"  answered   {time.perf_counter()-started:.2f}s total", "32"), flush=True)
            return content or "Jag fick inget svar från modellen. Försök gärna igen med lite mer information."
        if expected and any(call.get("function", {}).get("name") == expected for call in calls):
            expected = None
        messages.append({"role":"assistant","content":content,"tool_calls":calls})
        for call in calls:
            function = call.get("function", {}); name = function.get("name", "")
            arguments = function.get("arguments") or {}
            if isinstance(arguments, str): arguments = json.loads(arguments)
            print(base.paint(f"  action     {name}({json.dumps(arguments, ensure_ascii=False)})", "35"), flush=True)
            try:
                words = set(re.findall(r"[a-zåäö0-9-]+", text.casefold()))
                if name == "create_skill":
                    if not words & {"skapa", "create", "make", "bygg", "build"}: raise PermissionError("The current utterance did not explicitly request skill creation")
                    result = create_skill(**arguments)
                elif name == "install_skill":
                    if not words & {"installera", "install"}: raise PermissionError("The current utterance did not explicitly request installation")
                    result = install_skill(**arguments)
                elif name in SKILL_FUNCTIONS: result = SKILL_FUNCTIONS[name](**arguments)
                elif name in base.FUNCTIONS: result = base.FUNCTIONS[name](**arguments)
                else: raise ValueError("Unknown tool")
                if name == "read_installed_skill" and "error" not in result: skill_loaded = True
                serialized = json.dumps(result, ensure_ascii=False)
            except Exception as error:
                serialized = json.dumps({"error":str(error)}, ensure_ascii=False)
            print(base.paint(f"  result     {serialized[:1000]}", "34"), flush=True)
            messages.append({"role":"tool","tool_name":name,"content":serialized})
    raise RuntimeError("Skill agent exceeded six model steps")

def self_test():
    previous_skills = os.environ.get("DEMO13_SKILLS_DIR")
    previous_output = os.environ.get("DEMO13_OUTPUT_DIR")
    assert expected_skill_tool("Skapa en skill som hälsar välkommen") == "create_skill"
    assert expected_skill_tool("Skapa en logga med skillen ASKIART") == "read_installed_skill"
    assert expected_skill_tool("Kan du använda färdigheten ASKIART?") == "read_installed_skill"
    with tempfile.TemporaryDirectory(prefix="demo13-skills-") as directory, tempfile.TemporaryDirectory(prefix="demo13-output-") as output:
        os.environ["DEMO13_SKILLS_DIR"] = directory
        os.environ["DEMO13_OUTPUT_DIR"] = output
        created = create_skill("workshop-greeter", "Greet workshop visitors.",
                               "Greet the visitor warmly and mention the workshop title they provide.")
        assert created["status"] == "created" and Path(created["path"]).is_file()
        assert read_installed_skill("workshopgreeter")["name"] == "workshop-greeter"
        artifact = display_and_save_text("hello.txt", "HELLO")
        assert Path(artifact["path"]).read_text() == "HELLO"
    if previous_skills is None: os.environ.pop("DEMO13_SKILLS_DIR", None)
    else: os.environ["DEMO13_SKILLS_DIR"] = previous_skills
    if previous_output is None: os.environ.pop("DEMO13_OUTPUT_DIR", None)
    else: os.environ["DEMO13_OUTPUT_DIR"] = previous_output
    print(base.paint("  self-test  creation, fuzzy read, display, save, and rescan passed", "32"))

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--text", help="Run one test turn without a microphone")
    parser.add_argument("--no-play", action="store_true")
    parser.add_argument("--barge-in", action="store_true")
    parser.add_argument("--self-test", action="store_true", help="Test skill writes in a disposable temporary directory")
    args = parser.parse_args()
    if args.self_test:
        self_test(); return
    skill_prompt = (ROOT/"skills/voice-skill-agent/SKILL.md").read_text()
    print(base.paint("  skill      loaded voice-skill-agent", "36"), flush=True)
    print("Loading local Swedish speech models...", flush=True)
    stt, tts, history = load_stt("pianissimo"), load_tts("sv", "supertonic"), []
    print(f'  models     STT={stt["model_id"]}  LLM={base.MODEL}  TTS={tts["model_id"]}', flush=True)
    mic = None
    if not args.text:
        print("Requesting microphone access (approve Codex/Terminal if prompted)...", flush=True)
        mic = Microphone(); mic.stream.start()
    try:
        while True:
            if args.text: utterance = args.text
            else:
                partial = ""
                def show_partial(raw):
                    nonlocal partial
                    candidate = transcribe_pcm(stt, raw)
                    if candidate and candidate != partial:
                        partial = candidate; print(f'  live       "{partial}"', flush=True)
                raw = mic.capture(show_partial); started = time.perf_counter()
                utterance = transcribe_pcm(stt, raw)
                print(f'  transcript "{utterance}" ({time.perf_counter()-started:.2f}s)', flush=True)
            if not utterance: continue
            answer = run_skill_agent(utterance, history, skill_prompt)
            print("  voice      generating local speech...", flush=True); started = time.perf_counter()
            audio, rate = synthesize(tts, answer)
            print(f"  voice      synthesized in {time.perf_counter()-started:.2f}s", flush=True)
            if not args.no_play: play_audio(audio, rate, mic, args.barge_in)
            history = (history + [{"role":"user","content":utterance},{"role":"assistant","content":answer}])[-10:]
            if args.text: break
    except KeyboardInterrupt: print("\nVoice skill agent stopped.")
    finally:
        if mic: mic.stream.stop(); mic.stream.close()

if __name__ == "__main__": main()
